
#busari's token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjhmNDIwNDY3MWUwNzgwMGRiNGRmYWYiLCJlbWFpbCI6ImFiZHVsaGFrZWVtLmJ1c2FyaS5vbGF5aW5rYUBnbWFpbC5jb20iLCJpYXQiOjE3MjA3NjUzNjB9.FmLhADP5RA7Gxykbx74uu8CvdpceWMCMygAK_ibwcHs
#anifat's token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjkwZDA2ZmI3ZmQ4YjFhMDg5NmZlYjIiLCJlbWFpbCI6Im9sYWRlbGVhbmlmYXQwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjA3NjY2MDJ9.R-20Zi4Y_SwDBKXLbCFH5SnFOEBbjfS9xDPBwLPp2MA






### Register User
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "fullName": "Olayinka",
  "email": "Abdulhakeem.busari.olayinka@gmail.com",
  "password": "12345"
}



### Login User
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "Abdulhakeem.busari.olayinka@gmail.com",
  "password": "12345"
}

###

### Forgot Password
POST http://localhost:3000/user/forgot-password
Content-Type: application/json

{
  "email": "abdulhakeem.busari.olayinka@gmail.com"
}

###

### Reset Password
POST http://localhost:3000/user/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njk2MmVkMmJiZjA1OGQxNmE0MGFlYzAiLCJlbWFpbCI6IkFiZHVsaGFrZWVtLmJ1c2FyaS5vbGF5aW5rYUBnbWFpbC5jb20iLCJpYXQiOjE3MjExNDc3ODYsImV4cCI6MTcyMTE1MTM4Nn0.HFEB6czFLegoV-gmF2T5Mr8saR8Uxwj4utJf9BAeZME",
  "newPassword": "newPassword123"
}

###

### Get User Profile
GET http://localhost:3000/user/profile
Authorization: Bearer hgcsfsdfkjjnkytuiookopiyrvrhdsrtiupopo8764x6cc

###
