VCJ9..R-20Zi4Y_SwDBKXLbCFH5SnFOEBbjfS9xDPBwLPp2MA






### Register User
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "fullName": "Ola gold",
  "email": "hobusari@student.oauife.edu.ng",
  "password": "12345"
}



### Login User
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "hobusari@student.oauife.edu.ng",
  "password": "ola123"
}

###

### Forgot Password
POST http://localhost:3000/user/forgot-password
Content-Type: application/json

{
  "email":"Abdulhakeem.busari.olayinka@gmail.com"
}



### Reset Password
POST http://localhost:3000/user/reset-password
Content-Type: application/json

{
  "token": "6054ec9e-dee9-441c-bf8d-f214bf8daced",
  "newPassword": "newPassword123"
}

###

### Get User Profile
GET http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTFlMTNhMTMyNjAyYzU5NjBiZmQ5MSIsImVtYWlsIjoiaG9idXNhcmlAc3R1ZGVudC5vYXVpZmUuZWR1Lm5nIiwiaWF0IjoxNzIxODg1NjgwfQ.F799JSBjf_rGWuafTVpWTUjFbaZzhvlpsCr6SLPUkqI