VCJ9..R-20Zi4Y_SwDBKXLbCFH5SnFOEBbjfS9xDPBwLPp2MA






### Register User
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "fullName": "Olayinka",
  "email": "Abdulhakeem.busari.olayinka@gmail.com",
  "password": "12345"
}



### Login User
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "Abdulhakeem.busari.olayinka@gmail.com",
  "password": "12345"
}

###

### Forgot Password
POST http://localhost:3000/user/forgot-password
Content-Type: application/json

{
  "email":"Abdulhakeem.busari.olayinka@gmail.com"
}



### Reset Password
POST http://localhost:3000/user/reset-password
Content-Type: application/json

{
  "token": "6054ec9e-dee9-441c-bf8d-f214bf8daced",
  "newPassword": "newPassword123"
}

###

### Get User Profile
GET http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTYyZWQyYmJmMDU4ZDE2YTQwYWVjMCIsImVtYWlsIjoiQWJkdWxoYWtlZW0uYnVzYXJpLm9sYXlpbmthQGdtYWlsLmNvbSIsImlhdCI6MTcyMTQ1OTM1Mn0.w5HiNvN5ywm2jL9o3ZHxSbjEOgpx5yrlLGN4_j_1rkg